on:
  workflow_dispatch:
    inputs:
      tags:
  push:
    tags:
      - "*"
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

name: build
jobs:
  bof-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: NoZuFormatter
        run: |
          cpp_files=$(find . -type f -wholename "*-BOF/*.cpp")
          found=0
          for file in $cpp_files;
          do
              if grep -Hn "%zu" "$file";
              then
                  found=1
              fi
          done

          if [ $found -eq 1 ];
          then
              echo "Found %zu in file. Beacon does not support this, change it to %Iu"
              exit 1
          else
              exit 0
          fi
  build:
    runs-on: windows-2022
    needs: bof-lint
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          mkdir release
          cd CookieKatz-BOF && nmake all
          cd ..
          mv x64\Release\* release\
          cd CredentialKatz-BOF && nmake all
          cd ..
          mv x64\Release\* release\
      - name: ZipIt
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          path: '@zip.lst'
          filename: 'ChromeKatzBOFs.zip'
          command: 'echo ./chrome-katz.cna >> zip.lst && echo ./release/ >> zip.lst'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ChromeKatzBOFs.zip
