[package]
name = "RDP_Logger"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = {version =  "0.3.9", features = ["errhandlingapi", "handleapi","processthreadsapi", "tlhelp32","winuser","minwindef","windef"]}



