- name: Collect all facts
  ansible.builtin.setup:

- name: Create tailsacle Digital Ocean DNS records
  community.digitalocean.digital_ocean_domain_record:
    state: present
    type: A
    domain: "{{ op_domain_name }}"
    name: "{{ item }}"
    data: "{{ ansible_tailscale0.ipv4.address }}"
    oauth_token: "{{ digitalocean_token }}"
  with_items: "{{ tailscale_hostnames }}"
  when: deploy and warhorse.vm | regex_search("(?i).+('dns':.+'provider':\s'digitalocean')", multiline=True, ignorecase=True)

- name: Remove tailsacle Digital Ocean DNS records
  community.digitalocean.digital_ocean_domain_record:
    state: absent
    type: A
    domain: "{{ op_domain_name }}"
    name: "{{ item }}"
    data: "{{ ansible_tailscale0.ipv4.address }}"
    oauth_token: "{{ digitalocean_token }}"
  with_items: "{{ tailscale_hostnames }}"
  when: not deploy and warhorse.vm | regex_search("(?i).+('dns':.+'provider':\s'digitalocean')", multiline=True, ignorecase=True)

- name: Create tailsacle Linode DNS records
  linode.cloud.domain_record:
    state: present
    type: A
    domain: "{{ op_domain_name }}"
    name: "{{ item }}"
    target: "{{ ansible_tailscale0.ipv4.address }}"
    api_token: "{{ linode_token }}"
  with_items: "{{ tailscale_hostnames }}"
  when: deploy and warhorse.vm | regex_search("(?i).+('dns':.+'provider':\s'linode')", multiline=True, ignorecase=True)

- name: Remove tailsacle Linode DNS records
  linode.cloud.domain_record:
    state: absent
    type: A
    domain: "{{ op_domain_name }}"
    name: "{{ item }}"
    target: "{{ ansible_tailscale0.ipv4.address }}"
    api_token: "{{ linode_token }}"
  with_items: "{{ tailscale_hostnames }}"
  when: not deploy and warhorse.vm | regex_search("(?i).+('dns':.+'provider':\s'linode')", multiline=True, ignorecase=True)
