[package]
name = "Api_Hooking"
version = "0.1.0"
edition = "2024"

[dependencies]
widestring = "1.2.0"
windows = { version = "0.61.1", features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_UI_WindowsAndMessaging",
] }