# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "not-malware"
include-before = ["msvc-release.cmake"]

[target.dbgeng]
type = "shared"
sources = ["src/not-malware/main.cpp"]
compile-features = ["cxx_std_11"]
