[package]
name = "Alternate_Data_Stream"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = {version = "0.3.9", features = ["fileapi","handleapi", "heapapi","minwinbase","winbase","winnt"] }


