[package]
name = "Data_collector"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
sysinfo = "0.31.3"
walkdir = "2.5.0"
whoami = "1.5.1"
winapi = { version = "0.3.9", features = ["winnt", "winuser", "fileapi", "sysinfoapi", "processthreadsapi", "psapi","winbase"] }
winreg = "0.52.0"
