[package]
authors = ["5mukx", "smukx.site"]
categories = ["development-tools", "os", "security"]
edition = "2021"
keywords = ["process-ghosting", "windows", "security", "research", "malware-development"]
license = "MIT"
name = "GhostingProcess"
readme = "README.md"
repository = "https://github.com/Whitecat18/Rust-for-Malware-Development"
version = "0.1.0"

[dependencies]
ntapi = {version = "0.4.0"}
winapi = {version = "0.3.9", features = ["winuser", "winsock2", "synchapi", "fileapi", "errhandlingapi", "winbase", "memoryapi", "processenv", "userenv"]}
