[package]
name = "lookupprivilegevalue"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["ntstatus", "processthreadsapi", "errhandlingapi", "securitybaseapi", "winbase", "winnt", "wtypesbase"] }
ntapi = "0.4"