---
- name: Generating Terraform Azure Resource
  template:
    src: templates/azure/terraform_azure_resource.tf.j2
    dest: "{{ terraform_project_path }}/azure_resource.tf"
  when: warhorse | regex_search("(?i).+('provider':\s'azure')", multiline=True, ignorecase=True)

- name: Generating Terraform Azure CDN
  template:
    src: templates/azure/terraform_azure_cdn.tf.j2
    dest: "{{ terraform_project_path }}/azure_cdn.tf"
  when: warhorse.vm | regex_search("(?i).+('cdn':.+'provider':\s'azure')", multiline=True, ignorecase=True)

# - name: Generating Terraform Azure Appservice files
#   template:
#     src: templates/redirector/iis/{{ item }}.j2
#     dest: "{{ terraform_project_path }}/redirector/iis/{{ item }}"
#   with_items:
#   - applicationHost.xdt
#   - index.html
#   - web.conf

# - name: Generating Terraform Azure Appservice
#   template:
#     src: templates/azure/terraform_azure_appservice.tf.j2
#     dest: "{{ terraform_project_path }}/azure_appservice.tf"