name: Install podman 4.*
runs:
  using: composite
  steps:
    - run: if dpkg -l golang-github-containers-image ; then sudo apt-get remove -y golang-github-containers-image ; fi
      shell: bash -euxo pipefail {0}
    - run: |
        curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_$(lsb_release -rs)/Release.key \
          | gpg --dearmor \
          | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
      shell: bash -euxo pipefail {0}
    - run: |
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] \
          https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_$(lsb_release -rs)/ /" \
          | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
      shell: bash -euxo pipefail {0}
    - run: sudo apt-get update -y
      shell: bash -euxo pipefail {0}
    - run: sudo apt-get install -y podman skopeo
      shell: bash -euxo pipefail {0}
