[package]
name = "uac-bypass-cmstp"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.11.0", features = ["v4"] }
winapi = {version = "0.3.9", features = [
    "psapi", 
    "winuser", 
    "handleapi", 
    "minwindef",
    "processthreadsapi", 
]}
