apiVersion: v1
kind: Service
metadata:
  name: agent
  namespace: nonprod
  labels:
    app: agent
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5520
      targetPort: 5520
      protocol: TCP
  selector:
    app: agent
