[package]
name = "no_crt"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = true 
lto = true
codegen-units = 1
opt-level = "z"

[dependencies]
