[package]
name = "base_addr_locator"
version = "0.1.0"
edition = "2021"
authors = ["5mukx", "smukx.site"]
repository = "https://github.com/Whitecat18/Rust-for-Malware-Development"
keywords = ["windows", "security", "research", "address-locator"]
categories = ["development-tools", "os", "security"]
license = "MIT"
readme = "README.md"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "winnt", "libloaderapi"] }

