[package]
name = "ecscape"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.88"
aws-credential-types = "1.2.4"
aws-sdk-ecs = { version = "1.91.0", features = [
    "behavior-version-latest",
    "rustls",
] }
aws-sdk-s3 = { version = "1.100.0", features = [
    "behavior-version-latest",
    "rustls",
] }
aws-sdk-secretsmanager = { version = "1.82.0", features = [
    "behavior-version-latest",
    "rustls",
] }
aws-sigv4 = "1.3.3"
aws-types = "1.3.8"
chrono = { version = "0.4.41", features = ["serde"] }
clap = { version = "4.5.41", features = ["derive", "env"] }
futures-util = "0.3.31"
mimalloc = "0.1.47"
num_cpus = "1.17.0"
regex = "1.11.1"
reqwest = { version = "0.12.22", default-features = false, features = [
    "rustls-tls",
    "json",
] }
rustls = { version = "0.23.30", features = ["ring"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
sysinfo = "0.36.1"
tokio = { version = "1.47.0", features = ["full"] }
tokio-retry2 = "0.5.7"
tokio-tungstenite = { version = "0.27.0", features = [
    "rustls-tls-native-roots",
] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = "2.5.4"
uuid = { version = "1.17.0", features = ["v4"] }

[profile.release]
strip = "debuginfo"
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = false
