[package]
name = "earlycascade-injection"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["winbase", "fileapi", "heapapi", "libloaderapi", "processthreadsapi", "memoryapi", "winnt", "handleapi", "errhandlingapi"] }
