[package]
name = "Amsi_Bypass"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.12"
widestring = "1.2.0"
winapi = {version = "0.3.9", features = ["libloaderapi", "minwinbase", "errhandlingapi"] }
