# Example config.yaml for DigitalOcean
provider: digitalocean
credentials:
  token: your_do_token  # Personal Access Token from DigitalOcean
instance:
  name: my-vps
  region: nyc3  # e.g., nyc3, sfo3, etc.
  size: s-1vcpu-1gb  # e.g., s-1vcpu-1gb
  image: ubuntu-24-04-x64  # Latest LTS as of 2025
  ssh_key: /path/to/your/private_key.pem  # Local private key path (for SSH connection)
  ssh_pub_key_id: 12345678  # SSH key ID from DigitalOcean dashboard (upload pub key first)
provision:  # Special provisions to set up
  - docker  # Install official Docker Engine
  - podman  # Install Podman
  - python  # Ensure Python 3, pip, venv
tools_to_install:  # Additional apt packages
  - git
  - vim
repos_to_clone:  # Git repos to clone to /home/ubuntu/
  - https://github.com/robert-iw3/pen-testing.git
networking:
  firewall_rules:  # Inbound rules
    - protocol: tcp
      ports: [22, 80, 443]  # Single or list of ports
      sources: 0.0.0.0/0  # Be careful with sources!

# For AWS, change provider: aws
# credentials:
#   access_key: your_aws_access_key
#   secret_key: your_aws_secret_key
# instance:
#   ...
#   image: ami-0abcdef1234567890  # Latest Ubuntu 24.04 AMI ID for your region (find at https://cloud-images.ubuntu.com/locator/ec2/ search "noble amd64 hvm:ebs-ssd us-east-1")
#   key_name: my-aws-key  # Existing key pair name or will create new and save private to ssh_key path
# Note: AMIs change frequently; use AWS CLI: aws ec2 describe-images --owners 099720109477 --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-noble-24.04-amd64-server-*" "Name=state,Values=available" --query 'Images[*].[ImageId,CreationDate]' --output table --region us-east-1