[package]
name = "pipe_server"
version = "0.1.0"
edition = "2021"
authors = ["5mukx", "smukx.site"]

[dependencies]
winapi = { version = "0.3.9", features = ["winbase", "winnt", "namedpipeapi", "fileapi", "handleapi"] }