[package]
name = "check_dbg"
version = "0.1.0"
edition = "2021"
authors = ["", "5mukx.site"]
[dependencies]
winapi = { version = "0.3.9", features = [
    "handleapi",
    "tlhelp32",
    "processthreadsapi",
    "tlhelp32",
    "minwindef",
] }
