[toolchain]
channel = "nightly"

[build]
target = "x86_64-pc-windows-msvc" 
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=/SUBSYSTEM:CONSOLE",
    "-C", "link-arg=/NODEFAULTLIB",
    "-C", "link-arg=/ENTRY:main",
    "-C", "link-arg=kernel32.lib",
    "-Z", "fmt-debug=none",
    "-Z", "location-detail=none"
]

[unstable]
build-std = ["panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]