[package]
name = "ntsetinformationprocess"
version = "0.1.0"
edition = "2021"

[dependencies]
ntapi = "0.4"
winapi = { version = "0.3.9", features = [
    "errhandlingapi",
    "processthreadsapi",
    "securitybaseapi",
    "winbase",
] }
