CREATE DATABASE IF NOT EXISTS c2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE c2;

CREATE TABLE IF NOT EXISTS hosts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL UNIQUE,
  hostname VARCHAR(255),
  username VARCHAR(255),
  os VARCHAR(32),
  arch VARCHAR(32),
  peers JSON NULL,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS commands (
  id INT AUTO_INCREMENT PRIMARY KEY,
  command_text TEXT NOT NULL,
  os_filter VARCHAR(32) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS executed_commands (
  host_uuid CHAR(36) NOT NULL,
  command_id INT NOT NULL,
  executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (host_uuid, command_id),
  FOREIGN KEY (host_uuid) REFERENCES hosts(uuid) ON DELETE CASCADE,
  FOREIGN KEY (command_id) REFERENCES commands(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
