[workspace]
members = [
    "scepter-server",
    "scepter-agent",
    "scepter-common",
    "xtask",
]
resolver = "3"

[profile.release]
strip = "symbols"
panic = "abort"
opt-level = "z"
codegen-units = 1
lto = true