---
volumes:
    pgdata:
    deployments:

networks:
    redops:

x-common-vars-apps: &common-vars-apps
    security_opt: ['no-new-privileges:true']
    restart: unless-stopped
    env_file: ['.env']
    networks: ['redops']

services:

    postgres:
        <<: *common-vars-apps
        image: docker.io/postgres:17-alpine
        ports: ['5432:5432']
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
            POSTGRES_USER: ${POSTGRES_USER:-}
            POSTGRES_DB: ${POSTGRES_DB:-}
        volumes: ['pgdata:/var/lib/postgresql/data:Z']

    nucleus:
        <<: *common-vars-apps
        build:
            context: ./nucleus
            dockerfile: Dockerfile
        ports: ['${NUCLEUS_PORT:-}:${NUCLEUS_PORT:-}']
        environment:
            NUCLEUS_PORT: ${NUCLEUS_PORT:-}
            NUCLEUS_SECRET: ${NUCLEUS_SECRET:-}
            STORE_ENCRYPTION_KEY: ${POSTGRES_ENCRYPTION_KEY:-}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
            POSTGRES_USER: ${POSTGRES_USER:-}
            POSTGRES_DB: ${POSTGRES_DB:-}
            POSTGRES_HOST: postgres
            NODE_ENV: production
        volumes: ['deployments:/app/deployments:Z']
        depends_on: ['postgres']
        cap_add: ['net_admin']
        devices: ['/dev/net/tun']

    command:
        <<: *common-vars-apps
        build:
            context: ./command
            dockerfile: Dockerfile
        ports: ['3000:3000']
        environment:
            COMMAND_SECRET: ${COMMAND_SECRET:-}
            COMMAND_PORT: ${COMMAND_PORT:-}
            HOSTNAME: ${COMMAND_LISTEN_ADDR:-}
            NUCLEUS_PORT: ${NUCLEUS_PORT:-}
            NEXTAUTH_URL: http://${COMMAND_HOSTNAME:-}:${COMMAND_PORT:-}
            AUTH_TRUST_HOST: http://${COMMAND_HOSTNAME:-}:${COMMAND_PORT:-}
        depends_on: ['postgres']

    radar:
        <<: *common-vars-apps
        build:
            context: ./radar
            dockerfile: Dockerfile
        environment:
            VT_API_KEY: ${VT_API_KEY:-}
            NUCLEUS_PORT: ${NUCLEUS_PORT:-}
            NUCLEUS_SECRET: ${NUCLEUS_SECRET:-}
        depends_on:
            - postgres
            - nucleus


