[package]
name = "BlockHandle"
version = "0.1.0"
edition = "2021"
authors = ["smukx", "smukx.site"]

[dependencies]
winapi = { version = "0.3.9", features = ["winevt","processthreadsapi", "securitybaseapi", "sddl", "winnt","winerror", "winbase"] }