[package]
name = "Aes_Encryption"
version = "0.1.0"
edition = "2021"

[dependencies]

winapi = { version = "0.3.9", features = ["memoryapi", "processthreadsapi", "synchapi", "errhandlingapi", "handleapi"] }
libaes = "0.7.0"
rand = "0.9.0"
