[package]
name = "apc_queue_injection"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = [
    "processthreadsapi",
    "memoryapi",
    "errhandlingapi",
    "synchapi",
    "handleapi",
    "tlhelp32",
]}
