- name: 'setup : create evilginx2 network'
  become: true
  docker_network:
    name: '{{ evilginx2_docker_network }}'
    ipam_config:
      - subnet: '{{ evilginx2_network_ipam_subnet }}'
        gateway: '{{ evilginx2_network_ipam_gateway }}'
        iprange: '{{ evilginx2_network_ipam_iprange }}'