[package]
name = "scepter-common"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = {version = "0.59.0", features = ["default", "Win32_System_Pipes", "Win32_System_IO", "Win32_Storage_FileSystem", "Win32_Security", "Win32_Storage_FileSystem"]}
debug_print = "1.0.0"