[target.'cfg(all(target_os = "linux"))']
runner = "sudo -E"

[target.aarch64-apple-darwin]

[target.x86_64-apple-darwin]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-static"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-static"]

[env]
