---
- include: folders.yml
- include: ssh.yml
- include: inventory.yml
- include: generate.yml
- include: deployment.yml
- include: nginx.yml
  with_items: "{{ warhorse.vm }}"
  when: item.nginx.config_file is not defined and item.http_proxy == "nginx"
- include: evilginx2.yml
  with_items: "{{ warhorse.vm }}"
  when: item.evilginx2 is defined
- include: cobaltstrike.yml
  with_items: "{{ warhorse.vm }}"
  when: item.cobaltstrike is defined