[package]
name = "GitHub_API"
version = "0.1.0"
edition = "2021"
authors = ["5mukx", "https://x.com/5mukx", "smukx.site"]

[dependencies]
winapi = { version = "0.3.9", features = ["winhttp", "winbase", "sysinfoapi", "fileapi", "iphlpapi", "errhandlingapi", "winerror"] }