version: '3.9'

services:
  postgres:
    image: postgres
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: passpass
        POSTGRES_DB: db
        PGPASSWORD: passpass
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: passpass
      MYSQL_USER: user
      MYSQL_PASSWORD: passpass
      MYSQL_DATABASE: db
    ports:
      - "3306:3306" 