[package]
name = "hypnosis"
version = "0.1.0"
edition = "2021"
authors = ["5mukx", ""]

[dependencies]
winapi = { version = "0.3", features = [
    "debugapi",
    "errhandlingapi",
    "memoryapi",
    "minwinbase",
    "processthreadsapi",
    "winbase",
    "dbghelp"
]}