[package]
name = "NtMapViewOfSection"
version = "0.1.0"
edition = "2024"

[dependencies]
winapi = { version = "0.3", features = [
    "basetsd",
    "processthreadsapi",
    "handleapi",
    "libloaderapi",
    "winnt",
    "minwindef",
    "ntdef",
] }
