[package]
name = "PE_Analyzer1"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
winapi = { version = "0.3.9", features = [
    "winnt",
    "memoryapi",
    "processthreadsapi",
    "synchapi",
    "fileapi",
    "errhandlingapi",
    "handleapi",
    "heapapi"
] }
